name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: generate the cards
      run: |
        python -m pip install --upgrade pip
        pip install ads

        python gen.py
      env:
        ADS_DEV_KEY: ${{ secrets.ADS_KEY }}

    - name: Pushes to website
      uses: cpina/github-action-push-to-another-repository@master
      with:
        source-directory: '_posts/science'
        destination-github-username: 'grburgess'
        destination-repository-name: 'grburgess.github.io'
        user-email: jmichaelburgess@gmail.com    
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

    
        
